In [1]:
import tensorflow as tf
import numpy as np

<b>InteractiveSession()</b> <i>needs to be started to get output of variables, or else it will stored in data. We need to specify <b>.eval()</b> to get output.

In [3]:
tf.InteractiveSession()

In [4]:
a = tf.zeros((2,2))
b = tf.ones((2,2),np.float64).eval()
d = np.array([[2,3],[9,3]],np.float64)

<h1>Tensorflow</h1> and <h1> Numpy have many similar function</h1>, so it is important to check which type of data we are dealing with, either it is tensorflow or numpy array. We can check this by using <b>.dtype</b>

In [21]:
c = tf.reduce_sum(d,reduction_indices = 0).eval()

In [28]:
c

array([ 11.,   6.])

In [29]:
c.dtype

dtype('float64')

In [30]:
tf.InteractiveSession()
b = tf.ones((2,2),np.float64)
b.eval()

array([[ 1.,  1.],
       [ 1.,  1.]])

<div style=";">
<div><h2>Tensorflow functions for matrix handling</h2></div>
<div>
<table>
    <tr>
        <td style="left:200px"><font size="4"><b style="color:red;">.get_shape</b><i> it is equivalent to <b>.shape from numpy</b></i></font></td> </tr>
          <tr>

          <td style="left:200px"><font size="4"><b style="color:red;">tf.constant(x)</b><i>is used for storing constant values</i></font></td>
        </tr>
          <tr>

          <td style="left:200px"><font size="4"><b style="color:red;">.zeros(())</b><i>it is equivalent to <b>.shape from numpy.zeros()</b></i></font></td>
</tr>
          <tr>

          <td style="left:200px"><font size="4"><b style="color:red;">.get_shape</b><i>it is equivalent to <b>.shape from numpy</b></i></font></td>

    </tr>
    <tr>

          <td style="left:200px"><font size="4"><b style="color:red;">tf.assign(x,y)</b><i>it is equivalent to <b>x<-y, asssigning y's value to x </b></i></font></td>

    </tr>
     <tr>

          <td style="left:200px"><font size="4"><b style="color:red;">a = tf.matmul(x,y)</b><i> equivalent to np.dot(x,y)</i></font></td>
</tr>
</table>
<div style="padding-top:10px;">
</div>
<font size="4"><p><b><i>tf.session</i></b> has its own variable and run time, it basically creates an environment within Tensorflow<b><i>  sess.run(x)</i></b> to run that variable</p><b>when we do session.close() gpu releases the session, but variables still exists in memory buffer</b>
</font>
</div>
</div>
<div style="padding-top:10px;">
</div>
<div><font size="4"><b>var_1 = tf.Variable(0,name='var_1')</b>, where name is the title shown in graph during visualization, basically the parameteres will be assigned by <b>tf.variable()</b>, the other variables like x=3, are such statements would be <b>tensors</b>, and are used for input, <b><i>we will need to run sess.run(tf.global_variables_initializer()) to initialize all the parameters</i></b>, declared by tf.variable()</font></div>
<div style="padding-top:10px;">
</div>
<div><font size='4'>we can execute mutliple tensors in a session using sess.run([tensor_1,tensor_2])</font></div>
<div style="padding-top:10px;">
</div>
<div style="padding-top:15px;">
</div>
<div><font size='4'><b>inp1 = tf.placeholder(tf.float32)</b> in simple holds values from memory buffer, which can be used as input to other function. we use <b>.feed_dict{x:,x2:...xn:}</b> to provide input.</font></div>

Variables

    For parameters to learn
    Values can be derived from training
    Initial values are required (often random)

Placeholders

    Allocated storage for data (such as for image pixel data during a feed)
    Initial values are not required (but can be set, see tf.placeholder_with_default)


### here c.eval() takes values from interactivesession()
## TensorFlow computations define a  computation graph that has no numerical value until evaluated!

##
##

<font size="4">tf.variable_scope("  ",reuse=tf.AUTO_REUSE):
    var1 = tf.get_variable("variable102",[1])

    var3 = tf.get_variable("variable102",[1])
    var4 = tf.get_variable("variable102",[1])

we use scope, let's say we have some network, and many layers use same weights(variable), then we could share this variable, this sharing of variable is done by <b> tf.variable_scope("  ",reuse=tf.AUTO_REUSE) </b>, once it is done we can share variable without geting exception.. So, from now on we use <b> tf.get_variable("name", name,
    shape=None,
    dtype=None,
    initializer=None,
    regularizer=None,
    trainable=True,
    collections=None,
    caching_device=None,
    partitioner=None,
    validate_shape=True,
    use_resource=None,
    custom_getter=None,
    constraint=None
) </b> and it has more features, and make variable sharing easy</font>


# Pin a variable to GPU.
with tf.device("/gpu:0"):

    v = tf.Variable(...)



In [31]:
c.get_shape()
sess.run([output],feed_dict={inp1:[[1.,3.]],inp2:[[1],[3]]})

AttributeError: 'numpy.ndarray' object has no attribute 'get_shape'

### Listing 2-8. Define TensorFlow Constants


In [32]:
a = tf.constant(5)
b = tf.constant(9)
c = a*b
c.eval()

45

In [33]:
with tf.Session() as sess:
    a = tf.constant(45)
    print(c.eval())
    print(sess.run(a))

45
45


In [24]:
rw = tf.Variable(tf.random_normal((2,2)),name='lol')

In [25]:
with tf.Session()as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(rw))

[[-0.5528965   0.39970613]
 [-0.51575106  0.45685399]]


In [43]:
var_1 = tf.Variable(0,name='var_1')
add_op =  tf.add(var_1,tf.constant(1))
upd_op = tf.assign(var_1,add_op)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    lol = tf.constant(345678)
    upd_op = tf.constant(69)
    for i in range(5):
        print(sess.run(upd_op))
    sess.close()


69
69
69
69
69


In [38]:
lol.eval()

345678

In [41]:
with tf.Session() as sess2:
    sess2.run(tf.global_variables_initializer())
    
    for i in range(5):
        print(sess2.run(lol))
    sess2.close()

345678
345678
345678
345678
345678


In [45]:
x = tf.constant(1)
y = tf.constant(5)
z = tf.constant(7)
mul_x_y = x*y
final_op = mul_x_y + z
with tf.Session() as sess:
    print(sess.run([mul_x_y,final_op,x*5]))

[5, 12, 5]


In [47]:
inp1 = tf.placeholder(tf.float32)

In [66]:
#import tensorflow
import tensorflow as tf
#open a variable scope named 'scope1'
with tf.variable_scope("scope1"):
    #add a new variable to the graph
    var=tf.get_variable("variable4",[1])
    var = tf.Variable(89,name="lol")
#print the name of variable
print(var.name)

scope1_10/lol:0


In [103]:
#import tensorflow
import tensorflow as tf
#open a variable scope named 'scope1'
with tf.variable_scope("scope1",reuse=tf.AUTO_REUSE):
    
    #declare a variable named variable1
    var1 = tf.get_variable("variable102",[1])
    
    #set reuse flag to True
#     tf.get_variable_scope().reuse_variables()
    #just an assertion!
#     assert tf.get_variable_scope().reuse==True
    #declare another variable with same name
    var2=tf.get_variable("variable102",[1])
    var5 = tf.get_variable("variable103",[1])

assert var1==var2

In [104]:
with tf.variable_scope("scope1",reuse=tf.AUTO_REUSE):
    var1 = tf.get_variable("variable102",[1])

    var3 = tf.get_variable("variable102",[1])
    var4 = tf.get_variable("variable102",[1])

assert var4 == var3

In [110]:
import tensorflow as tf
#open a variable scope named 'scope1'
with tf.variable_scope("scope1",reuse=tf.AUTO_REUSE):
    
    #declare a variable named variable1
    var1 = tf.get_variable("variable10902",[1])
    
    #set reuse flag to True
#     tf.get_variable_scope().reuse_variables()
    #just an assertion!
#     assert tf.get_variable_scope().reuse==True
    #declare another variable with same name
    var2=tf.get_variable("variable10902",[1])
    var5 = tf.get_variable("variable10003",[1])

# assert var1==var2

## name_scope() has very little use, and i have yet to come across it